### ISSUE TITLE
`OpenedFileTable` needs to be shareable

### ISSUE THREAD

**Issue by michalfita** [nuta/kerla#106]
At the moment `Process::fork()` seem to clone the `OpenedFileTable` while for proper multithreading we have to have shared access to opened files following `clone(2)` semantics supported by the Linux Kernel.

Found during work on #88 and belongs to `Multithreading` milestone (I can't add myself).

More details in [the flags mask of `clone(2)`](https://man.archlinux.org/man/clone.2#The_flags_mask), scroll down to `CLONE_FILES`. I haven't checked yet how it's implemented in Linux Kernel.

**Comment by nuta** [comment]
I think so too. Similar to #107, let's use `Arc<SpinLock<OpenedFileTable>>` for `opened_files`.
