### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by NukeWilliams** [nuta/kerla#116]
hey @nuta  team so I am facing this issue
```
     CARGO  kernel
error: no such subcommand: `+nightly`
make[1]: *** [build-crate] Error 101
make: *** [build] Error 2
```

any ideas on fixing this issue?? pls help me

**Comment by Lurk** [comment]
Hi, have you tried this https://stackoverflow.com/a/63576016 ?

**Comment by NukeWilliams** [comment]
I am on macOS big sur

**Comment by nuta** [comment]
Please install [rustup](https://rustup.rs) and then follow steps in [documentation](https://kerla.dev/docs/quickstart.html#building).

**Comment by NukeWilliams** [comment]
hey @nuta so it is now building an is there any way to build iso??

**Comment by michalfita** [comment]
@nuta Shall this be closed if resolved?

**Comment by nuta** [comment]
> hey @nuta so it is now building. is there any way to build iso??

@NukeWilliams  You can use `make iso`
