### ISSUE TITLE
Introduce integration tests

### ISSUE THREAD

**Issue by nuta** [nuta/kerla#39]
Run a testing program on CI to check the functionality.

**Comment by nuta** [comment]
Closed by d156cb2aa8599f5de311135f453debfbf66587f4

**Comment by castarco** [comment]
It's not entirely clear to me how these tests work. Do they only check the exit status of executed programs?

**Comment by nuta** [comment]
For now, yes. I think we can improve integration tests by, for example, checking if stdout/stderr are identical with the execution on Linux.

**Comment by castarco** [comment]
I agree, that sounds like a good idea. Is it ok if I start working on that task? I didn't advance much on the `lseek` implementation, but I wanted to have a proper way to test it before.

**Comment by nuta** [comment]
Of course! 

JFYI, integration tests are bundled in the initramfs image here:

https://github.com/nuta/kerla/blob/abf990e8e810fa9fd19de31f0c7aed4627035c25/initramfs/Dockerfile#L65

In addition to existing shell script based integration tests, I think it would be helpful to add a simple Rust binary to test system calls.
